min_version = "2026.8.0"

[settings]
dotfiles.root = "~/.dotfiles"
dotfiles.default_mode = "symlink"

[dotfiles]
# Shell
"~/.zshenv" = {}
"~/.config/zsh" = "zsh"
"~/.gitconfig" = {}
"~/.config/tmux" = "tmux"
"~/.config/starship" = "starship"
"~/.config/yazi" = "yazi"
"~/.config/ripgrep" = "ripgrep"
"~/.config/mise" = "mise"
"~/.config/tms" = "tms"

# Scripts
"~/.local/bin" = { source = "scripts", mode = "symlink-each"}
