[mgr]
cwd = { fg = "#83a598" }
hovered = { fg = "#282828", bg = "#83a598" }
preview_hovered = { underline = true }
find_keyword = { fg = "#fabd2f", italic = true }
find_position = { fg = "#fe8019", bg = "reset", italic = true }
marker_selected = { fg = "#b8bb26", bg = "#b8bb26" }
marker_copied = { fg = "#fabd2f", bg = "#fabd2f" }
marker_cut = { fg = "#fb4934", bg = "#fb4934" }
tab_active = { fg = "#282828", bg = "#83a598" }
tab_inactive = { fg = "#a89984" }
tab_width = 1
border_symbol = "│"
border_style = { fg = "#665c54" }

[status]
separator_open = ""
separator_close = ""
separator_style = { fg = "#504945", bg = "#504945" }

# Mode indicators
mode_normal = { fg = "#a89984", bold = true }
mode_select = { fg = "#b8bb26", bold = true }
mode_unset = { fg = "#fb4934", bold = true }

# Progress indicators  
progress_label = { bold = true }
progress_normal = { fg = "#83a598", bg = "#3c3836" }
progress_error = { fg = "#fb4934", bg = "#3c3836" }

# Permissions
permissions_t = { fg = "#b8bb26" }
permissions_r = { fg = "#fabd2f" }
permissions_w = { fg = "#fb4934" }
permissions_x = { fg = "#83a598" }
permissions_s = { fg = "#d3869b" }

[select]
border = { fg = "#83a598" }
active = { fg = "#fe8019" }
inactive = {}

[input]
border = { fg = "#83a598" }
title = {}
value = {}
selected = { reversed = true }

[completion]
border = { fg = "#83a598" }
active = { bg = "#3c3836" }
inactive = {}

[tasks]
border = { fg = "#83a598" }
title = {}
hovered = { underline = true }

[which]
mask = { bg = "#1d2021" }
cand = { fg = "#83a598" }
rest = { fg = "#928374" }
desc = { fg = "#fe8019" }
separator = "  "
separator_style = { fg = "#504945" }

[help]
on = { fg = "#fe8019" }
exec = { fg = "#b8bb26" }
desc = { fg = "#928374" }
hovered = { bg = "#504945", bold = true }
footer = { fg = "#3c3836", bg = "#a89984" }

[filetype]
rules = [
  # Images
  { mime = "image/*", fg = "#b8bb26" },

  # Videos
  { mime = "video/*", fg = "#fabd2f" },
  { mime = "audio/*", fg = "#fabd2f" },

  # Archives
  { mime = "application/zip", fg = "#fe8019" },
  { mime = "application/gzip", fg = "#fe8019" },
  { mime = "application/x-tar", fg = "#fe8019" },
  { mime = "application/x-bzip*", fg = "#fe8019" },
  { mime = "application/x-7z-compressed", fg = "#fe8019" },
  { mime = "application/x-rar", fg = "#fe8019" },

  # Documents
  { mime = "application/pdf", fg = "#fb4934" },
  { mime = "application/msword", fg = "#83a598" },
  { mime = "application/vnd.ms-excel", fg = "#b8bb26" },

  # Code
  { name = "*.rs", fg = "#fe8019" },
  { name = "*.go", fg = "#83a598" },
  { name = "*.py", fg = "#fabd2f" },
  { name = "*.js", fg = "#fabd2f" },
  { name = "*.ts", fg = "#83a598" },
  { name = "*.jsx", fg = "#83a598" },
  { name = "*.tsx", fg = "#83a598" },
  { name = "*.vue", fg = "#b8bb26" },
  { name = "*.html", fg = "#fe8019" },
  { name = "*.css", fg = "#83a598" },
  { name = "*.scss", fg = "#d3869b" },
  { name = "*.json", fg = "#fabd2f" },
  { name = "*.toml", fg = "#fe8019" },
  { name = "*.yaml", fg = "#fe8019" },
  { name = "*.yml", fg = "#fe8019" },
  { name = "*.md", fg = "#83a598" },

  # Executables
  { name = "*.sh", fg = "#b8bb26" },
  { name = "*.bash", fg = "#b8bb26" },
  { name = "*.zsh", fg = "#b8bb26" },
  { name = "*.fish", fg = "#b8bb26" },

  # Config files
  { name = ".*", fg = "#928374" },
]

[icon]
"Desktop/" = "󰇄"
"Documents/" = "󰈙"
"Downloads/" = "󰉍"
"Pictures/" = "󰉏"
"Music/" = "󰝚"
"Movies/" = "󰿎"
"Videos/" = "󰿎"
"Public/" = "󰆍"
"Library/" = "󰌱"
"Development/" = "󰲋"
".git/" = "󰊢"
"node_modules/" = "󰎙"
"target/" = "󰆍"
"build/" = "󰆍"
"dist/" = "󰆍"

# File extensions
"*.rs" = "󱘗"
"*.go" = "󰟓"
"*.py" = "󰌠"
"*.js" = "󰌞"
"*.ts" = "󰛦"
"*.jsx" = "󰜈"
"*.tsx" = "󰜈"
"*.vue" = "󰡄"
"*.html" = "󰌝"
"*.css" = "󰌜"
"*.scss" = "󰌜"
"*.json" = "󰘦"
"*.toml" = "󰘦"
"*.yaml" = "󰘦"
"*.yml" = "󰘦"
"*.md" = "󰍔"
"*.txt" = "󰈙"
"*.pdf" = "󰈦"
"*.zip" = "󰿺"
"*.tar" = "󰿺"
"*.gz" = "󰿺"
"*.7z" = "󰿺"
"*.rar" = "󰿺"
"*.mp3" = "󰎆"
"*.mp4" = "󰿎"
"*.mkv" = "󰿎"
"*.avi" = "󰿎"
"*.mov" = "󰿎"
"*.jpg" = "󰉏"
"*.jpeg" = "󰉏"
"*.png" = "󰉏"
"*.gif" = "󰉏"
"*.svg" = "󰉏"
"*.ico" = "󰉏"
"*.webp" = "󰉏"
"*.exe" = "󰖳"
"*.msi" = "󰖳"
"*.deb" = "󰖳"
"*.rpm" = "󰖳"
"*.dmg" = "󰖳"
"*.app" = "󰖳"
"*.sh" = "󰨊"
"*.bash" = "󰨊"
"*.zsh" = "󰨊"
"*.fish" = "󰨊"
"*.vim" = "󰕷"
"*.lua" = "󰢱"
"*.dockerfile" = "󰡨"
"*.docker" = "󰡨"
"Dockerfile" = "󰡨"
"LICENSE" = "󰿃"
"README.md" = "󰍔"
"Makefile" = "󰍩"
"Cargo.toml" = "󱘗"
"package.json" = "󰎙"
"*.log" = "󰌱"
