#! /bin/sh

# Startups
picom &                                   # picom
pgrep -x sxhkd > /dev/null || sxhkd &     # sxhkd
$HOME/.config/polybar/launch.sh &         # polybar
xsetroot -cursor_name left_ptr &          # cursor
dunst &                                   # notification daemon
xrandr -s 2560x1440 &

# wallpaper
# feh --bg-fill /usr/share/backgrounds/bspwm/wall.png
feh --bg-fill ${HOME}/wallpapers/space.webp

# No of workspaces
bspc monitor -d 1 2 3 4 5 6

# focus with pointer
bspc config focus_follows_pointer true
# split ratio
bspc config split_ratio           0.52
bspc config borderless_monocle    true
bspc config gapless_monocle       true
# border colors basic
bspc config focused_border_color  '#D8DEE9'
bspc config normal_border_color   '#4C566A'
bspc config border_width          1
bspc config window_gap            10

# bspc rules
bspc rule -a Alacritty desktop='^1' follow=on focus=on
bspc rule -a firefox desktop='^2' follow=on focus=on
