# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.box = "bento/fedora-latest"
  
  config.vm.provider "virtualbox" do |vb|
    vb.memory = "2048"
    vb.cpus = 2
    vb.name = "fedora-latest"
  end
  
  config.vm.provision "shell", inline: <<-SHELL
    dnf update -y
    dnf install -y git curl sudo xz ca-certificates
    sudo -u vagrant git clone https://github.com/pa-oshea/dotfiles.git /home/vagrant/.dotfiles
    sudo -u vagrant chmod +x /home/vagrant/.dotfiles/install.sh /home/vagrant/.dotfiles/scripts/*.sh
    echo "Fedora Latest ready! SSH in and run: cd ~/.dotfiles && ./scripts/quick-setup.sh"
  SHELL
end
